### PR TITLE
Support for building ELF foreign-endian binaries

### PR DESCRIPTION
**Pull request by yd0b0N**
This PR modifies the ELF builder to support generation of binaries intended for foreign-endian architectures.

For now, this has only been tested with PPC32 built on x86_64.

### CODE REVIEW

**Comment by yd0b0N** [comment]
Looks ok now.

**Comment by romainthomas** [comment]
Thanks @yd0b0N. I'll do the review during the week.

**Comment by romainthomas** [comment]
I'll merge this PR after the 0.9 release.

**Comment by romainthomas** [comment]
Merged with d26f39829622d980a8f62368852da11c88fdebc6

**Pull request closed without merging**
