### PR TITLE
Sort static symbols in Builder for ELF.

### PR DESCRIPTION
**Pull request by Clcanny**
```cpp
// main.cpp
namespace {
int foo = 1;
}  // anonymous namespace

int bar = 2;

int main() {
}
```

```cpp
// test.cpp
#include <LIEF/ELF.hpp>
#include <memory>
#include <string>

int main(int argc, char* argv[]) {
  bool smart_mode = argc == 2 && argv[1] == std::string("true");
  std::unique_ptr<LIEF::ELF::Binary> binary(LIEF::ELF::Parser::parse("main"));
  std::string main_name = "main.cpp";
  std::string foo_name = "_ZN12_GLOBAL__N_13fooE";
  LIEF::ELF::Symbol main_sym = binary->get_static_symbol(main_name);
  LIEF::ELF::Symbol foo_sym = binary->get_static_symbol(foo_name);
  binary->remove_static_symbol(main_name);
  binary->remove_static_symbol(foo_name);
  binary->add_static_symbol(main_sym, smart_mode);
  binary->add_static_symbol(foo_sym, smart_mode);
  binary->write("main-modified");
}
```

```makefile
all :
        # Clean.
        rm -f main test main-modified
        # Compile.
        gcc main.cpp -O0 -ggdb -o main
        g++ -std=c++11 -O0 -ggdb test.cpp                                                    \
                -I/usr/include/LIEF-0.11.0-Linux/include -L/usr/lib/LIEF-0.11.0-Linux/lib -lLIEF \
        -o test
```

If run without smart mode, readelf will complain:

```bash
# ./test
# readelf --symbols main-modified | grep "Warning"
readelf: Warning: local symbol 71 found at index >= .symtab's sh_info value of 52
readelf: Warning: local symbol 72 found at index >= .symtab's sh_info value of 52
```

The reasons why readelf complains are:

1. Non-exported symbols should be sorted before exported symbols.
2. Information of .symtab section header records the first index of exported symbol.

If run with smart mode, readelf won't complain:

```bash
# ./test true
# readelf --symbols main-modified | grep "Warning"
```

1. I don't test it in Python because I don't know how to install it to Python.
2. It isn't smart enough, but I think it is a begining.

### CODE REVIEW

**Comment by Clcanny** [comment]
@romainthomas Hello, please review this change. Thanks a lot for your reviewing! (And please forget my poor English.)

**Comment by romainthomas** [comment]
Hello @Clcanny 
Thanks for this PR, I think that it would be better to make this kind of sort in the builder as it already done for the dynamic symbols:

https://github.com/lief-project/LIEF/blob/2145d79efb361eff87a3e5b05d9bf84720c491f6/src/ELF/Builder.tcc#L916-L923

**Comment by Clcanny** [comment]
> I think that it would be better to make this kind of sort in the builder as it already done for the dynamic symbols:
> 
> https://github.com/lief-project/LIEF/blob/2145d79efb361eff87a3e5b05d9bf84720c491f6/src/ELF/Builder.tcc#L916-L923

Hello @romainthomas , thanks for your review. I think the same logic should work for static symbols too.

Should I add the same logic for static symbols in the builder?

**Comment by romainthomas** [comment]
> Should I add the same logic for static symbols in the builder?

Yes, in the ``build_static_symbol()`` the first processing should be sorting the symbol

**Comment by Clcanny** [comment]
> Yes, in the `build_static_symbol()` the first processing should be sorting the symbol

Hello, I have changed the commit.

**Comment by romainthomas** [comment]
Merged with https://github.com/lief-project/LIEF/commit/588a7a3a04bfce43c88714954bbc27f1bca8d0d7

**Comment by Clcanny** [comment]
Thank you!

**Pull request closed without merging**
