### PR TITLE
Export BuildToolVersion and fix typo

### PR DESCRIPTION
**Pull request by mingwandroid**
Just a simple fix.. hope it's ok!

### CODE REVIEW

**Comment by romainthomas** [comment]
Humm it's already done here: https://github.com/lief-project/LIEF/blob/ab349aadc613fbd04ebc89e1c5e518bcf8334073/api/python/MachO/objects/pyBuildVersion.cpp#L45-L73

**Comment by mingwandroid** [comment]
Thanks. Something else is going on with my builds then. I get the same failure on Linux and macOS. I'll ping with more details later.

**Comment by mingwandroid** [comment]
Ah, I think the problem might be a typo ("BuildeVersion") in https://github.com/lief-project/LIEF/commit/6f967238#diff-48d65da68562e9918a1f502eb47ff2faR53

**Comment by mingwandroid** [comment]
Well, this is probably OK, but it does not fix my problem. I added some tracing for two symbols, one that is OK and also for this problematic one, and in my log I see:

```
x86_64-conda_cos6-linux-gnu/bin/ld: CMakeFiles/LIB_LIEF.dir/src/MachO/Binary.cpp.o: reference to _ZTIN4LIEF5MachO12BuildVersionE
x86_64-conda_cos6-linux-gnu/bin/ld: CMakeFiles/LIB_LIEF.dir/src/MachO/BinaryParser.cpp.o: reference to _ZTIN4LIEF5MachO12BuildVersionE
x86_64-conda_cos6-linux-gnu/bin/ld: CMakeFiles/LIB_LIEF.dir/src/MachO/Builder.cpp.o: reference to _ZTIN4LIEF5MachO12BuildVersionE
x86_64-conda_cos6-linux-gnu/bin/ld: CMakeFiles/LIB_LIEF.dir/src/MachO/BuildVersion.cpp.o: definition of _ZTIN4LIEF5MachO16BuildToolVersionE
x86_64-conda_cos6-linux-gnu/bin/ld: CMakeFiles/LIB_LIEF.dir/src/MachO/BuildVersion.cpp.o: definition of _ZTIN4LIEF5MachO12BuildVersionE
```

So I think the lack of any reference to this causes it to get stripped from the DSO.

**Comment by romainthomas** [comment]
You are right: I also forgot to export the symbol with ``LIEF_API``: https://github.com/lief-project/LIEF/blob/eeddc383938f4262bc1042f98ddeec150a4fca8d/include/LIEF/MachO/BuildVersion.hpp#L32
```cpp
class LIEF_API BuildToolVersion : public LIEF::Object {
```

**Comment by mingwandroid** [comment]
Thank you @romainthomas! I will test with just these two changes and report back to you.

**Comment by mingwandroid** [comment]
Do you want me to update this PR with this change too?

**Comment by mingwandroid** [comment]
Working now. Thank you for the support.

**Comment by romainthomas** [comment]
Thanks for the PR!

**Pull request merged**
