### PR TITLE
[PE] Add PowerPC Big Endian Machine ID (found on Xbox 360)

### PR DESCRIPTION
**Pull request by Aiden-Isik**
This PR adds the machine ID for big endian PowerPC (0x1F2)

It is undocumented by Microsoft and is used in Xbox 360 PE files. As far as I'm aware, it's used nowhere else.

### CODE REVIEW

**Comment by Aiden-Isik** [comment]
Don't merge yet, missed something

**Comment by Aiden-Isik** [comment]
Fixed.

**Comment by romainthomas** [comment]
Great thank you! (Do you have a binary with this machine type?)

**Comment by Aiden-Isik** [comment]
https://www.mediafire.com/file/n37vyyufi9r2r4k/backcompat.exe/file

Sourced from: https://web.archive.org/web/20090906002445/http://www.xbox.com/en-US/games/backwardscompatibility.htm

**Pull request merged**
