### PR TITLE
[WIP] allow external pybind11

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by romainthomas** [comment]
(The CI is failing)

**Comment by romainthomas** [comment]
In progress fixes in the branch [enhancement/ext-pybind11](https://github.com/lief-project/LIEF/tree/enhancement/ext-pybind11)

**Comment by romainthomas** [comment]
Merged with a15c6d1240feb9026c3ef8b55f1901d00c14ad29

**Comment by wolfv** [comment]
Awesome, thanks! Sorry for not finishing this fast enough

**Comment by romainthomas** [comment]
No problem :)

**Pull request closed without merging**
