### PR TITLE
Another Fix to the `write` Templates

### PR DESCRIPTION
**Pull request by yype**
This PR proposes another fix to https://github.com/lief-project/LIEF/issues/952.

Please check the latest discussion on that issue.

### CODE REVIEW

**Comment by romainthomas** [comment]
Hey @yype thank for the PR. 
I forgot to mention that the public headers (those in `include/`) must be C++11 compliant. From what I could see in your PR, it would mean inlining the `_v` `_t` helpers.

**Comment by yype** [comment]
> Hey @yype thank for the PR. I forgot to mention that the public headers (those in `include/`) must be C++11 compliant. From what I could see in your PR, it would mean inlining the `_v` `_t` helpers.

Got it. Just pushed an inlined version.

**Comment by romainthomas** [comment]
Looks great! Could you squash/rebase your commits to have a single one?

**Comment by yype** [comment]
> Looks great! Could you squash/rebase your commits to have a single one?

Sure! Done.

**Pull request merged**
