### PR TITLE
Fix MSVC runtime selection

### PR DESCRIPTION
**Pull request by mrexodia**

### CODE REVIEW

**Comment by romainthomas** [comment]
Looks good to me. Just waiting for the CI.

**Comment by romainthomas** [comment]
Looks good to me. Just waiting for the CI.

**Comment by romainthomas** [comment]
Thank you :)

**Comment by romainthomas** [comment]
(The Linux fail is my fault)

**Comment by mrexodia** [comment]
Locally I was getting a warning, but I’m not sure if it’s coming from LIEF or another library. Will need to investigate a bit more…

**Comment by mrexodia** [comment]
Looks like it’s coming from capstone. So on my side this is ready to merge.

**Pull request merged**
